### ISSUE TITLE
Allow controller to assume an intermediate IAM role at startup

### ISSUE THREAD

**Issue by seh** [mikkeloscar/kube-aws-iam-controller#15]
The vaguely similar _kiam_ controller allows use of what it calls (confusingly) [a "Server role"](https://github.com/uswitch/kiam/blob/master/docs/IAM.md#configuring-a-server-role)—an IAM role that the controller assumes when it starts, and which other application-scoped IAM roles must mention in a trust relationship in order for the controller to be able to assume them on behalf of requesting pods.

By offering this feature, application IAM role authors don't have to trust the IAM role initially held by the controller pod, which is likely to be the IAM role of the EC2 instance on which the controller pod is running. These instance-level roles are often established per cluster, if not per machine, and are neither sufficient abstract nor stable for application authors to reference in their trust relationships.

Consider emulating this feature here, introducing an optional command-line flag that allows specifying this intermediate "pod delegate" IAM role. If specified, the controller would immediately attempt to assume this role when it starts.

Adding this would require augmenting the documentation to show a more complete example of the following:
- The initial (machine-level) IAM role must allow assumption of the intermediate "pod delegate" role.
- The intermediate "pod delegate" role must trust the initial (machine-level) role.
- The intermediate "pod delegate" role must allow assumption of either all roles, or some narrower subset that encompasses what the cluster operators will allow.
- An application author's IAM role must trust the intermediate "pod delegate" role.

With this in place, application authors never need to know about these initial (machine-level) roles.

**Comment by mikkeloscar** [comment]
Right now this could be achieved with what's described here: https://github.com/mikkeloscar/kube-aws-iam-controller#bootstrap-in-non-aws-environment

But I totally agree that we should have it as a feature to make it simpler for operators. :+1:
